"""'Init'

Revision ID: 360ef6f12cb5
Revises: a859b81e74ff
Create Date: 2023-01-15 18:08:28.796127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '360ef6f12cb5'
down_revision = 'a859b81e74ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
