# Generated by Django 4.1.6 on 2023-02-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quotes', '0005_alter_quote_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='First',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Second',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
