# Generated by Django 4.1.6 on 2023-02-09 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_quotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='user',
        ),
    ]
