# Generated by Django 4.1.6 on 2023-02-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quotes', '0003_quote_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='quote',
            name='tags',
            field=models.CharField(default='', max_length=100),
        ),
    ]
